### ISSUE TITLE
Favorite stories list

### ISSUE THREAD

**Issue by pintjuk** [yawkat/FimFictionAPI#2]
To be able to get a list of favorite stories would be an useful feature . It is possible to get an rss feed using the user identifier. I am wondering if you are working on something like that ore if you have been planing to do it.
If you are not, then i would do it. And also if i was to implement the feature would you recommend using the standard xml parser ore is there any good rss parsers you can recommend? i have not don allot of web-page reading in Java.

**Comment by pintjuk** [comment]
i was talking about the tracked stories updates rss

**Comment by yawkat** [comment]
I did not know getting updates via RSS is possible. I will work on a good implementation. I perefer using the standard (raw) XML parser, as it is the fastest and least memory-intensive method.

**Comment by yawkat** [comment]
On another note: You can also use a SearchRequestFactory and set Favorite and Unread to true, and then use a Search Iterator to get the request. But that is slower than the new RSS method I implemented.

**Comment by pintjuk** [comment]
yeah i discovers you wiki and saw that, i like the search iterator more.

**Comment by yawkat** [comment]
Well, it would be suited for most uses, but the new one would be better for performance-sensitive things such as a cronjob server.
