### ISSUE TITLE
intresting crash

### ISSUE THREAD

**Issue by pintjuk** [yawkat/FimFictionAPI#4]
when i try to use the search iterator on the android (in a separate thread, using asynktask) the runtime crashes, the try statements does not catch the exception. i am going to investigate this further later, and it might just be that i have a bad build of the htmlparser. butt could you pleas red thes log and tell me what it tells you, it would be helpful   ![fail](https://f.cloud.github.com/assets/2887421/60823/7949e318-5c24-11e2-86cb-70ac78533256.png)

**Comment by yawkat** [comment]
Looks like you forgot to include all dependencies, htmllexer-2.1 to be exact :P You can find it on maven at http://mvnrepository.com/artifact/org.htmlparser/htmllexer/2.1 . I should probably write a build script or something.

**Comment by pintjuk** [comment]
that is why it is interesting, i heave not forgotten to include it. it runes fine in windows, eclipse reports no compiler errors but android android crashes as if htmllaxer does not exist.

**Comment by pintjuk** [comment]
does html laxer have documentation

**Comment by yawkat** [comment]
It probably does, but that shouldn't fix anything. Check the JAR file or whatever android apps are stored as for the htmllexer classes maybe. I have no idea. If that doesn't work either, decompile the lexer and insert the source files into your project.

**Comment by pintjuk** [comment]
apparently androids vm, dalvik, is not guaranteed to run bit-code compiled for regular java vm, so the sours code must be recompiled for dalvik in order to make it work. i tryd to de compile htmllexer.jar with jd it generated source code with some errors, i attempted to fix them with ought really knowing what i was doing so i probably broke it but was eventually able to compile it. Now the app is running without crashing but the API is not doing what it is supposed to, so i obviously broke the lexer source. I could try to find the programer who made the html laxe and try to get the corect source code, ore i could try to get help from people i know to decompile the jar correctly ore fix the source, ore i could find another open source html parser and build an api around it. no sure what option is the best.

**Comment by yawkat** [comment]
I will try making the API more stand-alone or offer Android-compatible versions for the libraries.

**Comment by pintjuk** [comment]
having the same issue with the StringEscapingUtility, just a heads up

**Comment by yawkat** [comment]
I doubt I will be able to remove the Apache commons because there aren't many libraries with complete HTML escaping out there, but I would be surprised if there was no android version of it because it is used in a lot of programs.

**Comment by pintjuk** [comment]
there is a newer version: apache.commons.lang3 ill will tray with that. but i took a look at the source and it looks very simple, so i will probably re implement it ore just copy the source and make it work.
